-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: newsapi-mart-source-daily-counts@1.0.0 (model: mart_newsapi__source_daily_counts)
{{ config(meta={"datacontract_cli": {"check": "mart_newsapi__source_daily_counts__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "mart_newsapi__source_daily_counts", "description": "Counts must be positive."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM mart_newsapi__source_daily_counts WHERE article_count <= 0
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
